// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolytechWebThings.Infrastructure.Database;

namespace PolytechWebThings.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210522093122_AddedRuleAndStepModels")]
    partial class AddedRuleAndStepModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.RuleDatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.Steps.ChangeThingStateStepDatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExecutionOrderPosition")
                        .HasColumnType("int");

                    b.Property<string>("NewPropertyState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RuleDatabaseModelId")
                        .HasColumnType("int");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<string>("ThingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RuleDatabaseModelId");

                    b.ToTable("ChangeThingStateStepDatabaseModel");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.Steps.ExecuteRuleStepDatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ExecutionOrderPosition")
                        .HasColumnType("int");

                    b.Property<int?>("RuleDatabaseModelId")
                        .HasColumnType("int");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RuleDatabaseModelId");

                    b.ToTable("ExecuteRuleStepDatabaseModel");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Users.UserDatabaseModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SessionToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Workspaces.WorkspaceDatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GatewayUrl")
                        .IsUnique();

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.Steps.ChangeThingStateStepDatabaseModel", b =>
                {
                    b.HasOne("PolytechWebThings.Infrastructure.Database.Rules.RuleDatabaseModel", null)
                        .WithMany("ChangeThingStateSteps")
                        .HasForeignKey("RuleDatabaseModelId");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.Steps.ExecuteRuleStepDatabaseModel", b =>
                {
                    b.HasOne("PolytechWebThings.Infrastructure.Database.Rules.RuleDatabaseModel", null)
                        .WithMany("ExecuteRuleSteps")
                        .HasForeignKey("RuleDatabaseModelId");
                });

            modelBuilder.Entity("PolytechWebThings.Infrastructure.Database.Rules.RuleDatabaseModel", b =>
                {
                    b.Navigation("ChangeThingStateSteps");

                    b.Navigation("ExecuteRuleSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
