using Domain.Entities.Common;

namespace Domain.Entities.Workspace
{
    internal class WorkspaceFactory : IFactory<NewWorkspaceCreationModel, IWorkspace>, IFactory<StoredWorkspaceCreationModel, IWorkspace>
    {
        public IWorkspace Create(NewWorkspaceCreationModel creationModel)
            => new Workspace(
                id: default, // id is generated by database
                name: creationModel.Name,
                gatewayUrl: creationModel.GatewayUrl,
                accessToken: creationModel.AccessToken,
                userEmail: creationModel.UserEmail);

        public IWorkspace Create(StoredWorkspaceCreationModel creationModel)
            => new Workspace(
                id: creationModel.Id,
                name: creationModel.Name,
                gatewayUrl: creationModel.GatewayUrl,
                accessToken: creationModel.AccessToken,
                userEmail: creationModel.UserEmail);
    }
}